version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    
    ports: 
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
    network_mode: bridge
  kibana:
    container_name: kibana
    image: kibana:7.5.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    network_mode: bridge
  logstash:
      image: docker.elastic.co/logstash/logstash:7.5.0
      container_name: logstash
      ulimits:
        memlock:
          soft: -1
          hard: -1
     
      volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/patterns:/usr/share/logstash/patterns
      - ./logstash.template.json:/usr/share/logstash/templates/logstash.template.json
      ports: 
      - 5044:5044
      links:
      - elasticsearch:elasticsearch
      depends_on:
        - elasticsearch
      network_mode: bridge
  filebeat:
      user: root
      container_name: filebeat
      image: docker.elastic.co/beats/filebeat:7.5.0
      links:
       - logstash:logstash
      depends_on:
       - logstash
      volumes:
          - /var/run/docker.sock:/host_docker/docker.sock
          - /var/lib/docker:/host_docker/var/lib/docker
          - /var/lib/docker/containers:/var/lib/docker/containers:ro
          - /home/sistema/ti/mern/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      command: --strict.perms=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      network_mode: bridge
    

